version: '2'
services:
  server:
    build: ./server
    hostname: bitly-server-api
    depends_on:
      - db
    volumes:
      - "./server:/app"
    ports:
      - "4444:4444"

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: urls-db
  client:
    build: ./client
    volumes:
      - "./client:/app"
    ports:
      - "3000:3000"
    depends_on:
      - server
    links:
      - server


