version: '2'
services:
  client:
    build: ./client
    volumes:
      - "./client:/app"
    ports:
      - "3000:3000"
    depends_on:
      - server
    links:
      - server

  server:
    build: ./server
    volumes:
      - "./server:/app"
    ports:
      - "4444:4444"

